# Generated by Django 4.0 on 2021-12-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_biking_alter_bikepartialexercise_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biking',
        ),
    ]
