# Generated by Django 4.0 on 2021-12-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_biking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
