# Generated by Django 3.2.8 on 2021-12-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_alter_biking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
