# Generated by Django 3.2.8 on 2022-01-29 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_alter_biking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biking',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
