# Generated by Django 3.2.8 on 2022-02-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20220130_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
