# Generated by Django 3.2.8 on 2022-03-07 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_auto_20220227_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dumbbell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.IntegerField(default=15)),
            ],
        ),
    ]
