# Generated by Django 3.2.8 on 2022-03-11 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0012_dumbbell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumbbell',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
